#!/bin/bash
# Add and Do or Prioritize in one command
# https://github.com/ginatrapani/todo.txt-cli/wiki/Creating-Add-ons%3A-Examples

action=$1
shift

[ "$action" = "usage" ] && {
  echo "  Customized add:"
  echo "    add pri PRIORITY \"THING I NEED TO DO +project @context\""
  echo "    add p PRIORITY \"THING I NEED TO DO +project @context\""
  echo "      add an item and prioritize it in one step"
  echo "    add x \"THING I NEEDED TO DO RIGHT NOW\""
  echo "      add an item and mark it as done in one step"
  echo ""
  exit
}

PRIORITY=false
DO=false
if [ "x$1" = "xpri" -o "x$1" = "xp" ] && [[ x"$2" = x[a-zA-Z] ]]; then
    PRIORITY=$2
    shift
    shift
elif [ x"$1" = x"x" ]; then
    DO=true
    shift
fi

if "$TODO_SH" command add "$@"; then
    # getting the number item: it's simply the last item added to the file
    line=`sed -n '$ =' "$TODO_FILE"`
    [ $PRIORITY != false ] && "$TODO_SH" command pri "$line" $PRIORITY
    $DO && "$TODO_SH" command do "$line"
fi
